---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: n8n
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: n8n
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./apps/n8n"
  prune: true
  timeout: 1m
